# Generated by Django 3.0.5 on 2021-04-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchandise',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='merchandise',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
