# Generated by Django 3.0.5 on 2021-04-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drape',
            name='author',
        ),
    ]
